include ../make.properties

default: compile

compile: 
	make -k -f zip.mk
	make -k -f client.mk
	make -k -f dom.mk
	make -k -f httpd.mk
	make -k -f isodate.mk
	make -k -f idhash.mk
	make -k -f lccm.mk
	make -k -f platform.mk
	make -k -f ramusage.mk
	make -k -f properties.mk
	make -k -f server.mk
	make -k -f sql.mk
	make -k -f string.mk
	make -k -f textquery.mk
	make -k -f textstore.mk
	make -k -f thread.mk
	make -k -f timer.mk
	make -k -f page.mk
	make -k -f regex.mk
	make -k -f xform.mk

clean:
	make -k -f zip.mk clean
	make -k -f client.mk clean
	make -k -f dom.mk clean
	make -k -f httpd.mk clean
	make -k -f isodate.mk clean
	make -k -f idhash.mk clean
	make -k -f lccm.mk clean
	make -k -f platform.mk clean
	make -k -f ramusage.mk clean
	make -k -f properties.mk clean
	make -k -f server.mk clean
	make -k -f sql.mk clean
	make -k -f string.mk clean
	make -k -f textquery.mk clean
	make -k -f textstore.mk clean
	make -k -f thread.mk clean
	make -k -f timer.mk clean
	make -k -f page.mk clean
	make -k -f regex.mk clean
	make -k -f xform.mk clean
