#ifndef _SRC_CLUCENE_CLUCENE_CONFIG_H
#define _SRC_CLUCENE_CLUCENE_CONFIG_H 1
 
/*
src/CLucene/clucene-config.h.
Generated
automatically
at
end
of
configure.
*/
/* config.h.tmp.  Generated by configure.  */
/* config.h.tmp.in.  Generated from configure.ac by autoheader.  */

/* Compiles in lite mode, without write ability */
/* #undef _CL_CLUCENE_LITE */

/* Disable multithreading */
/* #undef _CL_DISABLE_MULTITHREADING */

/* Define to 1 if you have the <algorithm> header file. */
#ifndef _CL_HAVE_ALGORITHM 
#define _CL_HAVE_ALGORITHM  1 
#endif

/* Define to 1 if you have the <ctype.h> header file. */
#ifndef _CL_HAVE_CTYPE_H 
#define _CL_HAVE_CTYPE_H  1 
#endif

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#ifndef _CL_HAVE_DIRENT_H 
#define _CL_HAVE_DIRENT_H  1 
#endif

/* Define to 1 if you have the <dlfcn.h> header file. */
#ifndef _CL_HAVE_DLFCN_H 
#define _CL_HAVE_DLFCN_H  1 
#endif

/* Define to 1 if you have the <errno.h> header file. */
#ifndef _CL_HAVE_ERRNO_H 
#define _CL_HAVE_ERRNO_H  1 
#endif

/* Define to 1 if you have the <ext/hash_map> header file. */
#ifndef _CL_HAVE_EXT_HASH_MAP 
#define _CL_HAVE_EXT_HASH_MAP  1 
#endif

/* Define to 1 if you have the <ext/hash_set> header file. */
#ifndef _CL_HAVE_EXT_HASH_SET 
#define _CL_HAVE_EXT_HASH_SET  1 
#endif

/* Define to 1 if you have the <fcntl.h> header file. */
#ifndef _CL_HAVE_FCNTL_H 
#define _CL_HAVE_FCNTL_H  1 
#endif

/* Define to 1 if the system has the type `float_t'. */
#ifndef _CL_HAVE_FLOAT_T 
#define _CL_HAVE_FLOAT_T  1 
#endif

/* Define to 1 if you have the <functional> header file. */
#ifndef _CL_HAVE_FUNCTIONAL 
#define _CL_HAVE_FUNCTIONAL  1 
#endif

/* Does not support new float byte<->float conversions */
#ifndef _CL_HAVE_FUNCTIONING_FLOAT_BYTE 
#define _CL_HAVE_FUNCTIONING_FLOAT_BYTE   
#endif

/* Define to 1 if you have the <hash_map> header file. */
/* #undef _CL_HAVE_HASH_MAP */

/* Define to 1 if you have the <hash_set> header file. */
/* #undef _CL_HAVE_HASH_SET */

/* Define to 1 if the system has the type `intptr_t'. */
#ifndef _CL_HAVE_INTPTR_T 
#define _CL_HAVE_INTPTR_T  1 
#endif

/* Define to 1 if you have the <inttypes.h> header file. */
#ifndef _CL_HAVE_INTTYPES_H 
#define _CL_HAVE_INTTYPES_H  1 
#endif

/* Define to 1 if you have the <list> header file. */
#ifndef _CL_HAVE_LIST 
#define _CL_HAVE_LIST  1 
#endif

/* Define to 1 if you have the `lltoa' function. */
/* #undef _CL_HAVE_LLTOA */

/* Define to 1 if you have the `lltow' function. */
/* #undef _CL_HAVE_LLTOW */

/* Define to 1 if long double works and has more range or precision than
   double. */
/* #undef _CL_HAVE_LONG_DOUBLE */

/* Define to 1 if you have the <map> header file. */
#ifndef _CL_HAVE_MAP 
#define _CL_HAVE_MAP  1 
#endif

/* Define to 1 if you have the <math.h> header file. */
#ifndef _CL_HAVE_MATH_H 
#define _CL_HAVE_MATH_H  1 
#endif

/* Define to 1 if you have the <memory.h> header file. */
#ifndef _CL_HAVE_MEMORY_H 
#define _CL_HAVE_MEMORY_H  1 
#endif

/* define if the compiler implements namespaces */
#ifndef _CL_HAVE_NAMESPACES 
#define _CL_HAVE_NAMESPACES   
#endif

/* Define if you have the nanosleep function */
#ifndef _CL_HAVE_NANOSLEEP 
#define _CL_HAVE_NANOSLEEP  1 
#endif

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef _CL_HAVE_NDIR_H */

/* Does not support new float byte<->float conversions */
/* #undef _CL_HAVE_NO_FLOAT_BYTE */

/* Does not support try/catch blocks */
/* #undef _CL_HAVE_NO_FUNCTION_TRY_BLOCKS */

/* Define to 1 if you have the `printf' function. */
#ifndef _CL_HAVE_PRINTF 
#define _CL_HAVE_PRINTF  1 
#endif

/* Define to 1 if you have the <pthread.h> header file. */
#ifndef _CL_HAVE_PTHREAD_H 
#define _CL_HAVE_PTHREAD_H  1 
#endif

/* Define to 1 if you have the <set> header file. */
#ifndef _CL_HAVE_SET 
#define _CL_HAVE_SET  1 
#endif

/* Define to 1 if you have the `snprintf' function. */
#ifndef _CL_HAVE_SNPRINTF 
#define _CL_HAVE_SNPRINTF  1 
#endif

/* Defined if the snprintf overflow test fails */
/* #undef _CL_HAVE_SNPRINTF_BUG */

/* Define to 1 if you have the `snwprintf' function. */
/* #undef _CL_HAVE_SNWPRINTF */

/* define if the compiler supports ISO C++ standard library */
#ifndef _CL_HAVE_STD 
#define _CL_HAVE_STD   
#endif

/* Define to 1 if you have the <stdarg.h> header file. */
#ifndef _CL_HAVE_STDARG_H 
#define _CL_HAVE_STDARG_H  1 
#endif

/* x */
#ifndef _CL_HAVE_STDEXCEPT 
#define _CL_HAVE_STDEXCEPT   
#endif

/* Define to 1 if you have the <stdint.h> header file. */
#ifndef _CL_HAVE_STDINT_H 
#define _CL_HAVE_STDINT_H  1 
#endif

/* Define to 1 if you have the <stdlib.h> header file. */
#ifndef _CL_HAVE_STDLIB_H 
#define _CL_HAVE_STDLIB_H  1 
#endif

/* define if the compiler supports Standard Template Library */
#ifndef _CL_HAVE_STL 
#define _CL_HAVE_STL   
#endif

/* Define to 1 if you have the <strings.h> header file. */
#ifndef _CL_HAVE_STRINGS_H 
#define _CL_HAVE_STRINGS_H  1 
#endif

/* Define to 1 if you have the <string.h> header file. */
#ifndef _CL_HAVE_STRING_H 
#define _CL_HAVE_STRING_H  1 
#endif

/* Define to 1 if you have the `strlwr' function. */
/* #undef _CL_HAVE_STRLWR */

/* Define to 1 if you have the `strtoll' function. */
#ifndef _CL_HAVE_STRTOLL 
#define _CL_HAVE_STRTOLL  1 
#endif

/* Define to 1 if you have the `strupr' function. */
/* #undef _CL_HAVE_STRUPR */

/* Defined if the swprintf test fails */
#ifndef _CL_HAVE_SWPRINTF_BUG 
#define _CL_HAVE_SWPRINTF_BUG   
#endif

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef _CL_HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef _CL_HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#ifndef _CL_HAVE_SYS_STAT_H 
#define _CL_HAVE_SYS_STAT_H  1 
#endif

/* Define to 1 if you have the <sys/timeb.h> header file. */
#ifndef _CL_HAVE_SYS_TIMEB_H 
#define _CL_HAVE_SYS_TIMEB_H  1 
#endif

/* Define to 1 if you have the <sys/types.h> header file. */
#ifndef _CL_HAVE_SYS_TYPES_H 
#define _CL_HAVE_SYS_TYPES_H  1 
#endif

/* Define to 1 if you have the <tchar.h> header file. */
/* #undef _CL_HAVE_TCHAR_H */

/* Define to 1 if you have the `tell' function. */
/* #undef _CL_HAVE_TELL */

/* Define to 1 if the system has the type `uint8_t'. */
#ifndef _CL_HAVE_UINT8_T 
#define _CL_HAVE_UINT8_T  1 
#endif

/* Define to 1 if you have the <unistd.h> header file. */
#ifndef _CL_HAVE_UNISTD_H 
#define _CL_HAVE_UNISTD_H  1 
#endif

/* Define to 1 if you have the <vector> header file. */
#ifndef _CL_HAVE_VECTOR 
#define _CL_HAVE_VECTOR  1 
#endif

/* Define to 1 if you have the `vsnwprintf' function. */
/* #undef _CL_HAVE_VSNWPRINTF */

/* Define to 1 if you have the <wchar.h> header file. */
#ifndef _CL_HAVE_WCHAR_H 
#define _CL_HAVE_WCHAR_H  1 
#endif

/* Define to 1 if the system has the type `wchar_t'. */
#ifndef _CL_HAVE_WCHAR_T 
#define _CL_HAVE_WCHAR_T  1 
#endif

/* Define to 1 if you have the `wcscasecmp' function. */
#ifndef _CL_HAVE_WCSCASECMP 
#define _CL_HAVE_WCSCASECMP  1 
#endif

/* Define to 1 if you have the `wcsicmp' function. */
/* #undef _CL_HAVE_WCSICMP */

/* Define to 1 if you have the `wcstod' function. */
#ifndef _CL_HAVE_WCSTOD 
#define _CL_HAVE_WCSTOD  1 
#endif

/* Define to 1 if you have the `wcstoll' function. */
#ifndef _CL_HAVE_WCSTOLL 
#define _CL_HAVE_WCSTOLL  1 
#endif

/* Define to 1 if you have the `wcsupr' function. */
/* #undef _CL_HAVE_WCSUPR */

/* Define to 1 if you have a functioning <wchar.h> header file. */
#ifndef _CL_HAVE_WCTYPE_H 
#define _CL_HAVE_WCTYPE_H   
#endif

/* Define to 1 if you have the `wprintf' function. */
/* #undef _CL_HAVE_WPRINTF */

/* Define to 1 if you have the `_filelength' function. */
/* #undef _CL_HAVE__FILELENGTH */

/* Name of package */
#ifndef _CL_PACKAGE 
#define _CL_PACKAGE  "clucene" 
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef _CL_PACKAGE_BUGREPORT 
#define _CL_PACKAGE_BUGREPORT  "" 
#endif

/* Define to the full name of this package. */
#ifndef _CL_PACKAGE_NAME 
#define _CL_PACKAGE_NAME  "" 
#endif

/* Define to the full name and version of this package. */
#ifndef _CL_PACKAGE_STRING 
#define _CL_PACKAGE_STRING  "" 
#endif

/* Define to the one symbol short name of this package. */
#ifndef _CL_PACKAGE_TARNAME 
#define _CL_PACKAGE_TARNAME  "" 
#endif

/* Define to the version of this package. */
#ifndef _CL_PACKAGE_VERSION 
#define _CL_PACKAGE_VERSION  "" 
#endif

/* The size of a `long', as computed by sizeof. */
/* #undef _CL_SIZEOF_LONG */

/* The size of a `unsigned char', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_CHAR */

/* The size of a `unsigned int', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_INT */

/* The size of a `unsigned long', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_LONG */

/* The size of a `unsigned long long', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED_LONG_LONG */

/* The size of a `unsigned __int64', as computed by sizeof. */
/* #undef _CL_SIZEOF_UNSIGNED___INT64 */

/* Define to 1 if the `S_IS*' macros in <sys/stat.h> do not work properly. */
/* #undef _CL_STAT_MACROS_BROKEN */

/* Define to 1 if you have the ANSI C header files. */
#ifndef _CL_STDC_HEADERS 
#define _CL_STDC_HEADERS  1 
#endif

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#ifndef _CL_TIME_WITH_SYS_TIME 
#define _CL_TIME_WITH_SYS_TIME  1 
#endif

/* Version number of package */
#ifndef _CL_VERSION 
#define _CL_VERSION  "0.9.10" 
#endif

/* Force into ascii mode */
/* #undef _CL__ASCII */

/* Conditional Debugging (only for when not in debug mode) */
/* #undef _CL__CND_DEBUG */

/* debuging option */
/* #undef _CL__DEBUG */

/* Number of bits in a file offset, on hosts where this is settable. */
#ifndef _CL__FILE_OFFSET_BITS 
#define _CL__FILE_OFFSET_BITS  64 
#endif

/* Define for large files, on AIX-style hosts. */
/* #undef _CL__LARGE_FILES */

/* Force into ucs2 mode */
/* #undef _CL__UCS2 */

/* If not already defined, then define as a datatype of *exactly* 32 bits. */
/* #undef __cl_uint32_t */

/* If not already defined, then define as a datatype of *exactly* 64 bits. */
/* #undef __cl_uint64_t */

/* If not already defined, then define as a datatype of *exactly* 8 bits. */
/* #undef __cl_uint8_t */
 
/* once:
_SRC_CLUCENE_CLUCENE_CONFIG_H
*/
#endif
